AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Resources:
  GetEnvData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.huirongxing.springboot.StreamLambdaHandler::handleRequest
      Runtime: java8
      Timeout : 30
      MemorySize: 1024
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /envdata
            Method: get

