AWSTemplateFormatVersion: 2010-09-09
Resources:
  GetEnvData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.huirongxing.springboot.StreamLambdaHandler
      Runtime: java8
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /envdata
            Method: get

